// Package export reproduces captured requests as safe shell commands and
// executable replay inputs. It never emits credential values: secrets are
// identified by name and rendered as environment placeholders.
package export

import (
	"net/http"
	"net/url"
	"regexp"
	"strings"

	"github.com/Zxyy-mo/llm-proxy-debugger/internal/store"
)

var (
	credentialHeaders = map[string]bool{
		"Authorization": true, "Proxy-Authorization": true, "Cookie": true,
		"X-Api-Key": true, "Api-Key": true, "X-Auth-Token": true, "X-Access-Token": true,
		"X-Goog-Api-Key": true, "Ocp-Apim-Subscription-Key": true, "X-Amz-Security-Token": true,
	}
	credentialHints  = []string{"authorization", "api-key", "apikey", "api_key", "token", "secret", "password", "cookie", "credential", "signature"}
	secretParameters = map[string]bool{
		"key": true, "api_key": true, "api-key": true, "apikey": true, "token": true, "access_token": true,
		"auth": true, "auth_token": true, "signature": true, "sig": true, "secret": true, "password": true,
	}
	// Schemes whose values depend on the request or a server challenge cannot be
	// reused by supplying a static secret.
	signedSchemes = map[string]bool{
		"aws4-hmac-sha256": true, "signature": true, "digest": true, "hawk": true, "oauth": true,
		"hmac": true, "hmac-sha256": true, "negotiate": true, "ntlm": true,
	}
	hopByHop = map[string]bool{
		"Connection": true, "Keep-Alive": true, "Proxy-Authenticate": true, "Proxy-Connection": true,
		"Te": true, "Trailer": true, "Transfer-Encoding": true, "Upgrade": true,
	}
	// Generated by proxies on the way; they describe the hop, not the request.
	forwardedHeaders = map[string]bool{"Forwarded": true, "X-Forwarded-For": true, "X-Forwarded-Host": true, "X-Forwarded-Proto": true, "Via": true}
	schemeToken      = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9-]*$`)
)

// IsCredentialHeader reports whether a header carries authentication material.
// The list is deliberately broad: a false positive only asks the operator to
// supply the value again, while a false negative would copy a secret.
func IsCredentialHeader(name string) bool {
	canonical := http.CanonicalHeaderKey(name)
	if credentialHeaders[canonical] {
		return true
	}
	lower := strings.ToLower(canonical)
	for _, hint := range credentialHints {
		if strings.Contains(lower, hint) {
			return true
		}
	}
	return false
}

// IsSecretParameter reports whether a query parameter name carries a secret,
// such as Google-style `?key=` API keys.
func IsSecretParameter(name string) bool {
	lower := strings.ToLower(name)
	if secretParameters[lower] {
		return true
	}
	for _, hint := range []string{"token", "secret", "password", "api_key", "apikey", "api-key", "signature"} {
		if strings.Contains(lower, hint) {
			return true
		}
	}
	return false
}

// HeaderCredential describes a credential header without retaining its value.
// The scheme (Bearer, Basic, ...) is kept so exports can show what to supply.
func HeaderCredential(name, value string) store.Credential {
	credential := store.Credential{Kind: "header", Name: http.CanonicalHeaderKey(name), Replayable: true}
	scheme, rest, found := strings.Cut(strings.TrimSpace(value), " ")
	if !found || !schemeToken.MatchString(scheme) {
		return credential
	}
	credential.Scheme = scheme
	lower := strings.ToLower(rest)
	if signedSchemes[strings.ToLower(scheme)] || strings.Contains(lower, "signature=") || strings.Contains(lower, "credential=") {
		credential.Replayable = false
	}
	return credential
}

// SkipHeader reports whether a header is regenerated per hop and therefore
// neither exported nor replayed.
func SkipHeader(name string, connection []string) bool {
	canonical := http.CanonicalHeaderKey(name)
	if hopByHop[canonical] || forwardedHeaders[canonical] || canonical == "Content-Length" || canonical == "Host" {
		return true
	}
	for _, value := range connection {
		for _, token := range strings.Split(value, ",") {
			if http.CanonicalHeaderKey(strings.TrimSpace(token)) == canonical {
				return true
			}
		}
	}
	return false
}

type queryPair struct {
	raw, name string
	secret    bool
}

func splitQuery(raw string) []queryPair {
	if raw == "" {
		return nil
	}
	var pairs []queryPair
	for _, part := range strings.Split(raw, "&") {
		if part == "" {
			continue
		}
		name, _, _ := strings.Cut(part, "=")
		if decoded, err := url.QueryUnescape(name); err == nil {
			name = decoded
		}
		pairs = append(pairs, queryPair{raw: part, name: name, secret: IsSecretParameter(name)})
	}
	return pairs
}

// RedactQuery masks secret parameter values for display while preserving order.
func RedactQuery(raw string) string {
	pairs := splitQuery(raw)
	if pairs == nil {
		return raw
	}
	parts := make([]string, 0, len(pairs))
	for _, pair := range pairs {
		if pair.secret {
			name, _, _ := strings.Cut(pair.raw, "=")
			parts = append(parts, name+"=****")
		} else {
			parts = append(parts, pair.raw)
		}
	}
	return strings.Join(parts, "&")
}

// Classify derives the forwarding profile of a request and the credentials it
// carried. Credential values are inspected only to record their scheme.
func Classify(r *http.Request) (*store.Forwarding, []store.Credential) {
	forwarding := &store.Forwarding{Scheme: r.URL.Scheme, Host: r.URL.Host, Path: r.URL.Path, Headers: make(http.Header)}
	if forwarding.Scheme == "" {
		forwarding.Scheme = "http"
		if r.TLS != nil {
			forwarding.Scheme = "https"
		}
	}
	if forwarding.Host == "" {
		forwarding.Host = r.Host
	}
	var credentials []store.Credential
	if r.URL.User != nil {
		credentials = append(credentials, store.Credential{Kind: "url", Name: "userinfo", Replayable: true})
	}
	var kept []string
	for _, pair := range splitQuery(r.URL.RawQuery) {
		if pair.secret {
			credentials = append(credentials, store.Credential{Kind: "query", Name: pair.name, Replayable: true})
		} else {
			kept = append(kept, pair.raw)
		}
	}
	forwarding.Query = strings.Join(kept, "&")
	connection := r.Header.Values("Connection")
	for name, values := range r.Header {
		if SkipHeader(name, connection) {
			continue
		}
		if IsCredentialHeader(name) {
			credentials = append(credentials, HeaderCredential(name, r.Header.Get(name)))
			continue
		}
		forwarding.Headers[http.CanonicalHeaderKey(name)] = append([]string(nil), values...)
	}
	return forwarding, credentials
}
